### ISSUE TITLE
Sorting stats incorrectly

### ISSUE THREAD

**Issue by Rekkyn** [phiresky/minecraft-stats#1]
Sorting arrays in javascript puts capital letters before lowercase letters, leading to a mismatch between the stat names and vales. This can be fixed by replacing

``` javascript
attrs = attrs.sort();
```

with

``` javascript
attrs = attrs.sort(function(a,b) {
        a = a.toLowerCase();
        b = b.toLowerCase();
        if( a == b) return 0;
        return a < b ? -1 : 1;
    });
```

This sorts it correctly and makes sure that each stat has the correct value.

**Comment by phiresky** [comment]
The problem was actually that I was sorting the data with `string.localeCompare` (which ignores casing) and the attribute names without that. Thats what I get for ignoring my todos..

Should be fixed now, please check.

``` typescript
attrs = attrs.sort((a,b) => a.localeCompare(b));
```
